#!/bin/bash

# Update system
sudo apt update -y

# Install MySQL Server
sudo apt install mysql-server -y

# Start and enable MySQL
sudo systemctl start mysql
sudo systemctl enable mysql

# Secure MySQL root access (no password for local testing)
sudo mysql <<EOF

CREATE DATABASE testdb;

USE testdb;

CREATE TABLE employees (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    department VARCHAR(100),
    salary INT
);

INSERT INTO employees (name, department, salary) VALUES
('Rahul Sharma', 'IT', 60000),
('Priya Verma', 'HR', 45000),
('Amit Singh', 'Finance', 70000),
('Neha Patel', 'Marketing', 50000),
('Vikas Kumar', 'Operations', 55000);

EOF

echo "MySQL setup completed successfully!"
